services:
  minio:
    image: quay.io/minio/minio
    container_name: minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345

    volumes:
      - ./data:/data

    command: server /data --console-address ":9001"

    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: mongo

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: animals

    volumes:
      - mongo_data:/data/db

    restart: unless-stopped

volumes:
  mongo_data: