spring.application.name=pet-adoption

spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USER}
spring.datasource.password=${LOCAL_DB_PASSWORD}

storage.type=${STORAGE_TYPE:mongo}

minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET:animals}

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uuid-representation=standard

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:1GB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:1GB}

spring.servlet.multipart.file-size-threshold=${FILE_SIZE_THRESHOLD:1MB}

spring.servlet.multipart.location=${UPLOAD_TEMP_DIR:${java.io.tmpdir}}

server.tomcat.max-swallow-size=-1

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public